text:
  fontSize: 11
  lineHeight: 1.2
  listLineHeight: 1
page:
  marginTop: 20
  marginBottom: 20
  marginHori: 15
  columnGap: 7
  columns: 2
  pageNumbers: true
  startPageNumber: 1
toc:
  enabled: true
  lineHeight: 1.3
  fontSize: 11
spaces:
  paragraph: 2.0
  heading: 3.0
paper:
  title: Paper
  authors: Anonymous
  debug: false
citation:
  enabled: true
  file: citations.bib
