text:
    fontSize: 11
    lineHeight: 1.2
    listLineHeight: 1
page:
    marginTop: 20
    marginBottom: 20
    marginHori: 15
    columnGap: 7
    columns: 2
    pageNumbers: true
    startPageNumber: 1
toc:
    enabled: true
    lineHeight: 1.3
    fontSize: 11
    heading: Table of Contents
spaces:
    paragraph: 2
    heading: 2
    code: 2
paper:
    title: Color Preferences for Nesting Material in the Zebra Finch (Poephila guttata)
    authors: University of Wisconsin-Madison
    debug: false
citation:
    enabled: true
    file: citations.bib
    heading: References
code:
    style: dracula
    fontSize: 10
    characterSpacing: 0
    lineNumbers: true
    mermaid: true
cover:
    enabled: true
    subtitle: Investigating the Role of Visual Cues in Nest Selection Behavior
